name: ci pipeline for frontend

on:
  push:

jobs:
  build:  
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.conan-cache.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - id: Build dependencies
        uses: ./.github/actions/build_deps

      - name: Build project
        working-directory: .
        run: |
          make build-release

  clang-format-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-19
          echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH
      
      - name: Run clang-format checks
        run: |
          find src -type f \( -name '*.hpp' -or -name '*.cpp' \) \
            -exec clang-format-19 --dry-run --Werror {} \+

  clang-tidy-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build dependencies
        uses: ./.github/actions/build_deps
      
      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-19
          echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH
      
      - name: Run clang-tidy
        run: |
          cp build/Release/compile_commands.json .
          run-clang-tidy -j$(nproc) -quiet
